add workflow to publish containers

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -58,3 +58,28 @@ jobs:
           asset_path: ${{ runner.workspace }}/downloads/Windows-x86_64/ziti-edge-tunnel-Windows_AMD64.zip
           asset_name: ziti-edge-tunnel-Windows_x86_64.zip
           asset_content_type: application/octet-stream
+
+  call-publish-containers:
+    name: Publish Container Images
+    runs-on: ubuntu-latest
+    needs: [ release ]
+    steps:
+      - name: Get the Version String from Git Tag
+        id: get_version
+        env:
+          GITHUB_REF: ${{ github.ref }}
+        run: |
+          ZITI_VERSION="${GITHUB_REF#refs/*/v}"
+          if [[ "${ZITI_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "DEBUG: ZITI_VERSION=${ZITI_VERSION}"
+            echo ZITI_VERSION="${ZITI_VERSION}" >> $GITHUB_OUTPUT
+          else
+            # fail the job because we could not obtain a valid version string from the Git ref
+            echo "ERROR: ZITI_VERSION=${ZITI_VERSION} is not a semver"
+            exit 1
+          fi
+      - name: Call the Publish Containers Workflow
+        uses: ./.github/workflows/publish-containers.yml
+        secrets: inherit
+        with:
+          ziti-version: ${{ needs.publish.outputs.ZITI_VERSION }}
